name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote add hf https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/siyam1/ML_Project
          git push hf main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
